(()=>{
  const NETKEIBA_RACE_IMPORT='https://qhzccahbevnqaoxdfnbx.supabase.co/functions/v1/netkeiba-race-import';
  const MEMORY_API_URL='https://qhzccahbevnqaoxdfnbx.supabase.co/functions/v1/keiba-memory-v55';
  const NK_FALLBACK_API='https://qhzccahbevnqaoxdfnbx.supabase.co/functions/v1/keiba-netkeiba-fallback';
  const NK_HISTORY_API='https://qhzccahbevnqaoxdfnbx.supabase.co/functions/v1/netkeiba-horse-history-v3';
  const NK_FORECAST_API='https://qhzccahbevnqaoxdfnbx.supabase.co/functions/v1/netkeiba-forecast-v2';
  const wait=()=>{
    if(typeof jraImport!=='function'||!document.getElementById('raceUrl')){setTimeout(wait,60);return;}
    if(window.__independentPatchApplied)return;
    window.__independentPatchApplied=true;
    const n=v=>Number.isFinite(+v)?+v:null, cleanName=v=>String(v||'').trim();
    function memoryRunToHistory(r){if(!r)return null;const passage=Array.isArray(r.passage)?r.passage:String(r.corners||'').split('-').map(Number).filter(Number.isFinite);return {date:r.date||'',venue:r.venue||r.course||'',surface:r.surface||'',distance:+(r.distance??r.dist)||0,going:r.going||'',rank:+(r.rank??r.pos)||0,last3f:Number.isFinite(+(r.last3f??r.last3))?+(r.last3f??r.last3):null,jockey:r.jockey||'',passage,field_size:+(r.field_size||0)||null,source:r.source||'netkeiba-memory'};}
    function currentRaceDate(){const ms=String(document.getElementById('raceUrl')?.value||'').match(/20\d{6}/g)||[];return ms.length?+ms[ms.length-1]:null;}
    function normalizeHistory(rows){const cutoff=currentRaceDate();return (rows||[]).map(memoryRunToHistory).filter(Boolean).filter(x=>x.rank&&x.distance).filter(x=>{if(!cutoff)return true;const m=String(x.date||'').match(/(20\d{2})[\/.-](\d{1,2})[\/.-](\d{1,2})/);return !m||(+m[1]*10000+(+m[2])*100+(+m[3]))<cutoff;});}
    function applyHistoryToHorse(h,rows,via='memory'){const all=[...(h.history||[]),...normalizeHistory(rows)],uniq=[],seen=new Set();for(const x of all.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))){const k=[x.date,x.venue,x.surface,x.distance,x.rank].join('|');if(seen.has(k))continue;seen.add(k);uniq.push(x);if(uniq.length>=5)break;}if(!uniq.length)return false;h.history=uniq;h.histScores=scoreLocalHistory(h.history);h.histScores.available=true;h.netkeibaVia=via;h.netkeibaRejected=false;h.netkeibaError='';mergeNetkeibaWithJra(h);return true;}
    function inferStyle(h){const rows=(h.history||[]).filter(r=>Array.isArray(r.passage)&&r.passage.length&&r.passage[0]>0);if(!rows.length)return ['逃','先','差','追'].includes(h.style)?h.style:'';const vals=rows.map(r=>Math.max(1,+r.passage[0])/(+r.field_size||18)).sort((a,b)=>a-b),x=vals[Math.floor(vals.length/2)];return x<=.14?'逃':x<=.36?'先':x<=.72?'差':'追';}
    function preentry(){return !!window.__preentryMode||/netkeiba\.com/i.test(String(document.getElementById('raceUrl')?.value||''));}
    function cleanLabels(){if(!preentry())return;document.querySelectorAll('.card').forEach(el=>{el.innerHTML=el.innerHTML.replace(/JRA実データ/g,'コース基礎データ').replace(/\s*\(netkeiba\)/g,'').replace(/騎手相性\s*：\s*(?:JRA前4走コンビ成績を反映|netkeiba過去走の騎乗情報を参考)/g,'騎手相性：過去走の騎乗情報を反映').replace(/騎手\s*：\s*現騎手×当馬のJRA前4走コンビ成績を反映/g,'騎手：過去走の騎乗情報を反映')});}
    nkFallback=async function(names,race_url){const horse_ids={};for(const h of horses||[])if(names.includes(h.name)){const id=String(h.netkeiba_horse_id||h.horse_id||'').trim();if(id)horse_ids[h.name]=id}const r=await fetch(NK_FALLBACK_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({names,race_url,horse_ids})}),j=await r.json().catch(()=>({results:[]}));if(!r.ok)throw new Error(j.error||'netkeiba再取得エラー');return j;};
    async function exactHistoryPass(list){if(!list.length)return;const items=list.map(h=>({name:h.name,id:String(h.netkeiba_horse_id||h.horse_id||'').trim()}));if(!items.some(x=>x.id))return;try{const r=await fetch(NK_HISTORY_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})}),j=await r.json().catch(()=>({results:[]}));if(!r.ok)return;for(const rr of j.results||[]){const h=horses.find(x=>cleanName(x.name)===cleanName(rr.name));if(h&&rr.available&&Array.isArray(rr.history)&&rr.history.length)applyHistoryToHorse(h,rr.history,'netkeiba-exact-id');}}catch(e){console.warn('exact history',e)}}
    async function fallbackPass(list){if(!list.length)return;try{const fb=await nkFallback(list.map(h=>h.name),document.getElementById('raceUrl').value);for(const rr of fb.results||[]){const h=horses.find(x=>cleanName(x.name)===cleanName(rr.name));if(h&&rr.available&&Array.isArray(rr.history)&&rr.history.length)applyHistoryToHorse(h,rr.history,rr.via||'netkeiba-id');}}catch(e){console.warn('fallback history',e)}}
    let historyLoading=false,historyLastKey='';
    loadNetkeibaHistories=async function({silent=false,force=false}={}){const runKey=horses.map(h=>`${h.name}:${h.netkeiba_horse_id||h.horse_id||''}`).join('|');if(historyLoading)return {ok:0,total:horses.length,skipped:true};if(!force&&historyLastKey===runKey)return {ok:horses.filter(h=>(h.history||[]).length).length,total:horses.length,skipped:true};historyLoading=true;try{if(!horses.length)return {ok:0,total:0};if(!silent)status('histStatus','netkeiba過去5走を全頭確認中…');let memRows=[];try{const mem=await memoryApi('horse_memory',{names:horses.map(h=>h.name)});memRows=mem.rows||[]}catch(e){}const mm=new Map(memRows.map(x=>[cleanName(x.horse_name),x.memory_json||{}]));for(const h of horses){const runs=mm.get(cleanName(h.name))?.runs||[];if(runs.length)applyHistoryToHorse(h,runs,'supabase-netkeiba-cache');}let need=horses.filter(h=>force||(h.history||[]).length<5);await exactHistoryPass(need);need=horses.filter(h=>(h.history||[]).length<5);await fallbackPass(need);if(preentry())for(const h of horses){const s=inferStyle(h);if(s)h.style=s}renderHorses();evalAll();cleanLabels();const ok=horses.filter(h=>(h.history||[]).length).length,totalRuns=horses.reduce((n,h)=>n+Math.min(5,(h.history||[]).length),0);const hc=document.getElementById('histCount');if(hc)hc.textContent='netkeiba '+ok+'/'+horses.length+'頭・合計'+totalRuns+'走';if(!silent)status('histStatus','netkeiba '+ok+'/'+horses.length+'頭・合計'+totalRuns+'走を使用。');historyLastKey=runKey;return {ok,total:horses.length,totalRuns};}catch(e){if(!silent)status('histStatus','netkeiba取得処理でエラー：'+(e.message||String(e)),true);return {ok:0,total:horses.length,error:e};}finally{historyLoading=false;}};
    async function refreshForecast(url,list){for(const h of list){h.forecast_odds=null;h.forecast_popularity=null;h.popularity=null;h.odds=null;}try{const r=await fetch(NK_FORECAST_API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,names:list.map(h=>h.name)})}),j=await r.json().catch(()=>({results:[]}));for(const rr of j.results||[]){const h=list.find(x=>cleanName(x.name)===cleanName(rr.name));if(!h)continue;const o=n(rr.odds),p=n(rr.popularity);if(o!==null)h.forecast_odds=h.odds=o;if(p!==null)h.forecast_popularity=h.popularity=p;}}catch(e){}}
    const baseJraImport=jraImport;jraImport=async function(url){const s=String(url||'').trim();if(!/netkeiba\.com/i.test(s)){window.__preentryMode=false;return baseJraImport(url)}const r=await fetch(NETKEIBA_RACE_IMPORT+'?t='+Date.now(),{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:s})}),j=await r.json().catch(()=>({error:'netkeiba出馬表の応答を読み込めません'}));if(!r.ok)throw new Error(j.error||'netkeiba出馬表取込エラー');window.__preentryMode=true;j.horses=(j.horses||[]).map((h,i)=>({...h,no:i+1,jra_history:[],provisional:true,provisional_no:true,forecast_odds:null,forecast_popularity:null,popularity:null,odds:null}));await refreshForecast(s,j.horses);j.meta={...(j.meta||{}),source:'netkeiba',provisional:true,odds_type:'forecast'};return j;};
    const input=document.getElementById('raceUrl');if(input)input.placeholder='JRA または netkeiba のレースURL';
  };wait();
})();