(()=>{
  const NETKEIBA_RACE_IMPORT='https://qhzccahbevnqaoxdfnbx.supabase.co/functions/v1/netkeiba-race-import';
  const NK_FALLBACK_API='https://qhzccahbevnqaoxdfnbx.supabase.co/functions/v1/keiba-netkeiba-fallback';
  const NK_HISTORY_API='https://qhzccahbevnqaoxdfnbx.supabase.co/functions/v1/netkeiba-horse-history-v3';
  const NK_FORECAST_API='https://qhzccahbevnqaoxdfnbx.supabase.co/functions/v1/netkeiba-forecast-v2';
  const wait=()=>{if(typeof jraImport!=='function'||!document.getElementById('raceUrl')){setTimeout(wait,60);return;}if(window.__independentPatchApplied)return;window.__independentPatchApplied=true;
    const n=v=>Number.isFinite(+v)?+v:null, cleanName=v=>String(v||'').trim();
    function memoryRunToHistory(r){if(!r)return null;const passage=Array.isArray(r.passage)?r.passage:String(r.corners||'').split('-').map(Number).filter(Number.isFinite);return {date:r.date||'',venue:r.venue||r.course||'',surface:r.surface||'',distance:+(r.distance??r.dist)||0,going:r.going||'',rank:+(r.rank??r.pos)||0,last3f:n(r.last3f??r.last3),jockey:r.jockey||'',passage,field_size:+(r.field_size||0)||null,source:r.source||'netkeiba-memory'};}
    function raceDate(){const m=String(document.getElementById('raceUrl')?.value||'').match(/20\d{6}/g)||[];return m.length?+m[m.length-1]:null;}
    function normalize(rows){const cutoff=raceDate();return(rows||[]).map(memoryRunToHistory).filter(x=>x&&x.rank&&x.distance).filter(x=>{if(!cutoff)return true;const m=String(x.date||'').match(/(20\d{2})[\/.-](\d{1,2})[\/.-](\d{1,2})/);return !m||(+m[1]*10000+(+m[2])*100+(+m[3]))<cutoff;});}
    function applyHistory(h,rows,via){const all=[...(h.history||[]),...normalize(rows)],u=[],seen=new Set();for(const x of all.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))){const k=[x.date,x.venue,x.surface,x.distance,x.rank].join('|');if(seen.has(k))continue;seen.add(k);u.push(x);if(u.length>=5)break;}if(!u.length)return false;h.history=u;h.histScores=scoreLocalHistory(u);h.histScores.available=true;h.netkeibaVia=via||'netkeiba';h.netkeibaRejected=false;h.netkeibaError='';mergeNetkeibaWithJra(h);return true;}
    function inferStyle(h){const rows=(h.history||[]).filter(r=>Array.isArray(r.passage)&&r.passage.length&&r.passage[0]>0);if(!rows.length)return['逃','先','差','追'].includes(h.style)?h.style:'';const vals=rows.map(r=>Math.max(1,+r.passage[0])/(+r.field_size||18)).sort((a,b)=>a-b),x=vals[Math.floor(vals.length/2)];return x<=.14?'逃':x<=.36?'先':x<=.72?'差':'追';}
    function preentry(){return!!window.__preentryMode||/netkeiba\.com/i.test(String(document.getElementById('raceUrl')?.value||''));}
    function cleanLabels(){if(!preentry())return;document.querySelectorAll('.card').forEach(el=>{el.innerHTML=el.innerHTML.replace(/\s*\(netkeiba\)/g,'').replace(/騎手相性\s*：\s*(?:JRA前4走コンビ成績を反映|netkeiba過去走の騎乗情報を参考)/g,'騎手相性：過去走の騎乗情報を反映').replace(/騎手\s*：\s*現騎手×当馬のJRA前4走コンビ成績を反映/g,'騎手：過去走の騎乗情報を反映')});}
    async function fetchJson(url,body,ms){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms||10000);try{const r=await fetch(url,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:c.signal});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'取得エラー');return j;}finally{clearTimeout(t);}}
    async function exact(list){if(!list.length)return;try{const j=await fetchJson(NK_HISTORY_API,{items:list.map(h=>({name:h.name,id:String(h.netkeiba_horse_id||h.horse_id||'').trim()}))},12000);for(const rr of j.results||[]){const h=horses.find(x=>cleanName(x.name)===cleanName(rr.name));if(h&&rr.available&&Array.isArray(rr.history))applyHistory(h,rr.history,'netkeiba-exact-id');}}catch(e){console.warn('history exact',e)}}
    async function fallback(list){if(!list.length)return;try{const ids={};for(const h of list){const id=String(h.netkeiba_horse_id||h.horse_id||'').trim();if(id)ids[h.name]=id}const j=await fetchJson(NK_FALLBACK_API,{names:list.map(h=>h.name),race_url:document.getElementById('raceUrl').value,horse_ids:ids},12000);for(const rr of j.results||[]){const h=horses.find(x=>cleanName(x.name)===cleanName(rr.name));if(h&&rr.available&&Array.isArray(rr.history))applyHistory(h,rr.history,rr.via||'netkeiba-id');}}catch(e){console.warn('history fallback',e)}}
    let loading=false,lastKey='';loadNetkeibaHistories=async function({silent=false,force=false}={}){const key=horses.map(h=>`${h.name}:${h.netkeiba_horse_id||h.horse_id||''}`).join('|');if(loading)return;if(!force&&lastKey===key)return;loading=true;try{if(!silent)status('histStatus','netkeiba過去5走を全頭確認中…');let need=horses.filter(h=>(h.history||[]).length<5);await exact(need);need=horses.filter(h=>(h.history||[]).length<5);await fallback(need);if(preentry())horses.forEach(h=>{const s=inferStyle(h);if(s)h.style=s});renderHorses();evalAll();cleanLabels();const ok=horses.filter(h=>(h.history||[]).length).length,runs=horses.reduce((a,h)=>a+Math.min(5,(h.history||[]).length),0),hc=document.getElementById('histCount');if(hc)hc.textContent=`netkeiba ${ok}/${horses.length}頭・合計${runs}走`;if(!silent)status('histStatus',`netkeiba ${ok}/${horses.length}頭・合計${runs}走を使用。`);lastKey=key;}catch(e){if(!silent)status('histStatus','netkeiba取得処理でエラー：'+(e.message||e),true);}finally{loading=false;}};
    async function refreshForecast(url,list){try{const j=await fetchJson(NK_FORECAST_API,{url,names:list.map(h=>h.name)},8000);for(const rr of j.results||[]){const h=list.find(x=>cleanName(x.name)===cleanName(rr.name));if(!h)continue;const o=n(rr.odds),p=n(rr.popularity);if(o!==null)h.forecast_odds=h.odds=o;if(p!==null)h.forecast_popularity=h.popularity=p;}}catch(e){console.warn('forecast skipped',e)}}
    const baseJraImport=jraImport;jraImport=async function(url){const s=String(url||'').trim();if(!/netkeiba\.com/i.test(s)){window.__preentryMode=false;return baseJraImport(url)}const j=await fetchJson(NETKEIBA_RACE_IMPORT,{url:s},15000);window.__preentryMode=true;j.horses=(j.horses||[]).map((h,i)=>({...h,no:i+1,jra_history:[],provisional:true,provisional_no:true,forecast_odds:null,forecast_popularity:null,popularity:null,odds:null}));refreshForecast(s,j.horses);j.meta={...(j.meta||{}),source:'netkeiba',provisional:true,odds_type:'forecast'};return j;};
    const input=document.getElementById('raceUrl');if(input)input.placeholder='JRA または netkeiba のレースURL';
  };wait();
})();